export const POI_TYPE_LABELS: Record<number, string> = {
  1: "City",
  2: "Country",
  3: "State",
  4: "Church",
  5: "Monastery",
  6: "Cathedral",
  7: "Temple",
  8: "Botanical Garden",
  9: "Archaeological Site",
  10: "Bridge",
  11: "Square",
  12: "Market",
  13: "Building",
  14: "Town Hall",
  15: "Station",
  16: "Viewpoint",
  17: "Museum",
  18: "Landmark",
  19: "Statue",
  20: "Zoo",
  21: "Park",
  22: "Landscape",
  23: "Hill",
  24: "National Park",
  25: "Garden",
  26: "Lake",
  27: "City State",
  28: "Citadel",
  29: "Restaurant",
  30: "Bar",
  31: "Airport",
  32: "Hotel",
  33: "District",
  34: "Region",
  35: "Subregion",
  36: "Cafe",
  37: "Mountain",
  38: "Island",
  39: "Mausoleum",
  40: "Cemetery",
  41: "Library",
  42: "University",
  43: "Other",
  44: "Theater",
  45: "Palace",
  46: "Fortification",
  47: "Waterfall",
  48: "Port",
  49: "Fountain",
  50: "Castle",
};
